// =====================
// 공통 회사 채용 데이터
// =====================
var COMPANY_DATA = [
    // ── 기존 데이터 (1~11) ─────────────────────────────────────────

    // 거리: ~330m
    {
        id: 1,
        name: "카카오",
        logo: "🟡",
        industry: "IT·인터넷",
        position: "프론트엔드 개발자",
        type: "정규직",
        salary: "5,000 ~ 8,000만원",
        minSalary: 5000,
        experience: "3년 이상",
        expMin: 3,
        scores: {salary:72,welfare:68,growth:85,balance:60,career:80,stability:55},
        education: "학력무관",
        deadline: "2026-04-30",
        tags: ["React", "TypeScript", "재택가능"],
        lat_offset: +0.003,
        lng_offset: +0.002,
        address: "서울 성남시 분당구",
        employees: "5,000명+",
        rating: 4.2,
        welfare_items: ["스톡옵션", "유연근무", "식비 지원", "자기계발비"],
        work_style: ["하이브리드", "주 2회 재택", "자율 출퇴근"],
    },
    // 거리: ~490m
    {
        id: 2,
        name: "네이버",
        logo: "🟢",
        industry: "IT·인터넷",
        position: "백엔드 개발자",
        type: "정규직",
        salary: "6,000 ~ 10,000만원",
        minSalary: 6000,
        experience: "5년 이상",
        expMin: 5,
        scores: {salary:88,welfare:72,growth:90,balance:45,career:92,stability:70},
        education: "학력무관",
        deadline: "2026-05-15",
        tags: ["Java", "Spring", "MSA"],
        lat_offset: -0.002,
        lng_offset: +0.004,
        address: "경기 성남시 분당구",
        employees: "4,000명+",
        rating: 4.0,
        welfare_items: ["사택 지원", "자녀 교육비", "의료비 지원", "사내 카페"],
        work_style: ["주 3회 재택", "유연 출퇴근", "탄력근무제"],
    },
    // 거리: ~310m
    {
        id: 3,
        name: "라인플러스",
        logo: "🟩",
        industry: "IT·인터넷",
        position: "iOS 개발자",
        type: "정규직",
        salary: "4,500 ~ 7,000만원",
        minSalary: 4500,
        experience: "2년 이상",
        expMin: 2,
        scores: {salary:65,welfare:70,growth:88,balance:65,career:85,stability:60},
        education: "학력무관",
        deadline: "2026-04-20",
        tags: ["Swift", "UIKit", "글로벌"],
        lat_offset: +0.001,
        lng_offset: -0.003,
        address: "서울 강남구",
        employees: "2,000명+",
        rating: 4.3,
        welfare_items: ["글로벌 워크샵", "어학 지원", "건강검진", "복지포인트"],
        work_style: ["하이브리드", "완전 자율 출퇴근"],
    },
    // 거리: ~490m
    {
        id: 4,
        name: "쿠팡",
        logo: "🔴",
        industry: "이커머스",
        position: "데이터 엔지니어",
        type: "정규직",
        salary: "5,500 ~ 9,000만원",
        minSalary: 5500,
        experience: "3년 이상",
        expMin: 3,
        scores: {salary:78,welfare:55,growth:65,balance:35,career:70,stability:80},
        education: "학력무관",
        deadline: "상시채용",
        tags: ["Python", "Spark", "AWS"],
        lat_offset: -0.004,
        lng_offset: -0.001,
        address: "서울 송파구",
        employees: "50,000명+",
        rating: 3.8,
        welfare_items: ["연봉 상위 수준", "성과 인센티브", "식대 제공"],
        work_style: ["사무실 근무", "교대 근무 없음"],
    },
    // 거리: ~580m
    {
        id: 5,
        name: "토스",
        logo: "🔵",
        industry: "핀테크",
        position: "Product Designer",
        type: "정규직",
        salary: "5,000 ~ 8,000만원",
        minSalary: 5000,
        experience: "3년 이상",
        expMin: 3,
        scores: {salary:74,welfare:82,growth:92,balance:78,career:95,stability:50},
        education: "학력무관",
        deadline: "2026-04-25",
        tags: ["Figma", "UX리서치", "프로덕트"],
        lat_offset: +0.005,
        lng_offset: +0.001,
        address: "서울 강남구",
        employees: "1,000명+",
        rating: 4.5,
        welfare_items: ["스톡옵션", "무제한 휴가", "점심 제공", "장비 지원"],
        work_style: ["완전 재택 가능", "자율 출퇴근", "결과 중심"],
    },
    // 거리: ~550m
    {
        id: 6,
        name: "당근마켓",
        logo: "🟠",
        industry: "IT·인터넷",
        position: "Android 개발자",
        type: "정규직",
        salary: "4,000 ~ 7,000만원",
        minSalary: 4000,
        experience: "신입·경력",
        expMin: 0,
        scores: {salary:60,welfare:85,growth:80,balance:82,career:75,stability:45},
        education: "학력무관",
        deadline: "상시채용",
        tags: ["Kotlin", "Compose", "애자일"],
        lat_offset: -0.001,
        lng_offset: -0.005,
        address: "서울 서초구",
        employees: "500명+",
        rating: 4.4,
        welfare_items: ["반려동물 동반 출근", "무제한 간식", "수평 문화"],
        work_style: ["하이브리드", "주 3회 재택", "자율 출퇴근"],
    },
    // 거리: ~550m | 계약직 | 이커머스
    {
        id: 7,
        name: "11번가",
        logo: "🛒",
        industry: "이커머스",
        position: "마케팅 기획자",
        type: "계약직",
        salary: "3,000 ~ 4,000만원",
        minSalary: 3000,
        experience: "1년 이상",
        expMin: 1,
        scores: {salary:42,welfare:50,growth:40,balance:70,career:45,stability:55},
        education: "학력무관",
        deadline: "상시채용",
        tags: ["퍼포먼스마케팅", "GA4", "콘텐츠기획"],
        lat_offset: +0.0025,
        lng_offset: +0.0040,
        address: "서울 중구",
        employees: "1,500명+",
        rating: 3.6,
        welfare_items: ["복지포인트", "명절 상여", "생일 휴가"],
        work_style: ["사무실 근무", "주 5일"],
    },
    // 거리: ~1.1km | 정규직 | 핀테크
    {
        id: 8,
        name: "카카오페이",
        logo: "💳",
        industry: "핀테크",
        position: "리스크 분석가",
        type: "정규직",
        salary: "8,000 ~ 12,000만원",
        minSalary: 8000,
        experience: "5년 이상",
        expMin: 5,
        scores: {salary:90,welfare:68,growth:75,balance:50,career:88,stability:72},
        education: "학력무관",
        deadline: "2026-06-01",
        tags: ["머신러닝", "금융데이터", "SQL"],
        lat_offset: -0.0055,
        lng_offset: +0.0085,
        address: "서울 강남구",
        employees: "800명+",
        rating: 4.1,
        welfare_items: ["스톡옵션", "금융 복지", "건강검진", "자기계발비"],
        work_style: ["하이브리드", "주 2회 재택"],
    },
    // 거리: ~220m | 인턴 | IT·인터넷
    {
        id: 9,
        name: "야놀자",
        logo: "🏨",
        industry: "IT·인터넷",
        position: "서비스 기획 인턴",
        type: "인턴",
        salary: "2,500만원",
        minSalary: 2500,
        experience: "신입",
        expMin: 0,
        scores: {salary:30,welfare:55,growth:60,balance:75,career:50,stability:40},
        education: "학력무관",
        deadline: "2026-05-01",
        tags: ["서비스기획", "PPT", "사용자리서치"],
        lat_offset: +0.0010,
        lng_offset: +0.0015,
        address: "서울 마포구",
        employees: "1,200명+",
        rating: 3.9,
        welfare_items: ["여행 할인", "숙박 할인", "간식 제공"],
        work_style: ["사무실 근무", "자율 출퇴근"],
    },
    // 거리: ~1.8km | 프리랜서 | IT·인터넷
    {
        id: 10,
        name: "크래프톤",
        logo: "🎮",
        industry: "IT·인터넷",
        position: "게임 서버 개발자",
        type: "프리랜서",
        salary: "6,000 ~ 9,000만원",
        minSalary: 6000,
        experience: "3년 이상",
        expMin: 3,
        scores: {salary:82,welfare:62,growth:70,balance:40,career:65,stability:60},
        education: "학력무관",
        deadline: "상시채용",
        tags: ["C++", "언리얼엔진", "멀티플레이"],
        lat_offset: -0.0090,
        lng_offset: +0.0140,
        address: "서울 강남구",
        employees: "3,000명+",
        rating: 4.2,
        welfare_items: ["게임 제공", "사내 피트니스", "성과급"],
        work_style: ["사무실 근무", "플렉스타임"],
    },
    // 거리: ~2.7km | 계약직 | 핀테크
    {
        id: 11,
        name: "뱅크샐러드",
        logo: "🥗",
        industry: "핀테크",
        position: "데이터 분석가",
        type: "계약직",
        salary: "4,000 ~ 6,000만원",
        minSalary: 4000,
        experience: "2년 이상",
        expMin: 2,
        scores: {salary:58,welfare:65,growth:72,balance:68,career:62,stability:42},
        education: "학력무관",
        deadline: "2026-05-31",
        tags: ["Python", "Tableau", "A/B테스트"],
        lat_offset: +0.0130,
        lng_offset: +0.0220,
        address: "서울 서초구",
        employees: "300명+",
        rating: 4.0,
        welfare_items: ["복지포인트", "금융 컨설팅", "팀 워크샵"],
        work_style: ["하이브리드", "주 2회 재택"],
    },

    // ── 추가 데이터: 3km ~ 10km 구간 ──────────────────────────────

    // 거리: ~3.5km | 정규직 | IT·인터넷
    {
        id: 12,
        name: "우아한형제들",
        logo: "🍔",
        industry: "IT·인터넷",
        position: "풀스택 개발자",
        type: "정규직",
        salary: "5,000 ~ 8,000만원",
        minSalary: 5000,
        experience: "3년 이상",
        expMin: 3,
        scores: {salary:70,welfare:78,growth:68,balance:55,career:65,stability:58},
        education: "학력무관",
        deadline: "2026-05-20",
        tags: ["Node.js", "React", "배달"],
        lat_offset: +0.0200,
        lng_offset: +0.0240,
        address: "서울 송파구",
        employees: "3,000명+",
        rating: 4.1,
        welfare_items: ["배달 할인", "식대 지원", "성과 인센티브"],
        work_style: ["하이브리드", "자율 출퇴근"],
    },
    // 거리: ~4.2km | 계약직 | 이커머스
    {
        id: 13,
        name: "SSG닷컴",
        logo: "🛍️",
        industry: "이커머스",
        position: "UX 기획자",
        type: "계약직",
        salary: "3,500 ~ 5,000만원",
        minSalary: 3500,
        experience: "2년 이상",
        expMin: 2,
        scores: {salary:50,welfare:60,growth:45,balance:65,career:48,stability:68},
        education: "학력무관",
        deadline: "2026-04-28",
        tags: ["Figma", "사용자조사", "앱기획"],
        lat_offset: -0.0260,
        lng_offset: +0.0300,
        address: "서울 중구",
        employees: "2,500명+",
        rating: 3.7,
        welfare_items: ["쇼핑 할인", "복지포인트", "명절 상여"],
        work_style: ["사무실 근무", "유연 출퇴근"],
    },
    // 거리: ~5.5km | 정규직 | 핀테크 | 상시채용
    {
        id: 14,
        name: "케이뱅크",
        logo: "🏦",
        industry: "핀테크",
        position: "신용평가 모델러",
        type: "정규직",
        salary: "7,000 ~ 10,000만원",
        minSalary: 7000,
        experience: "4년 이상",
        expMin: 4,
        scores: {salary:85,welfare:64,growth:62,balance:52,career:80,stability:85},
        education: "학력무관",
        deadline: "상시채용",
        tags: ["통계", "머신러닝", "금융"],
        lat_offset: +0.0350,
        lng_offset: +0.0350,
        address: "서울 광진구",
        employees: "600명+",
        rating: 4.0,
        welfare_items: ["금융 우대", "건강검진", "자기계발비"],
        work_style: ["사무실 근무", "주 5일", "탄력근무"],
    },
    // 거리: ~6.8km | 인턴 | IT·인터넷
    {
        id: 15,
        name: "NHN",
        logo: "🕹️",
        industry: "IT·인터넷",
        position: "QA 엔지니어 인턴",
        type: "인턴",
        salary: "2,800만원",
        minSalary: 2800,
        experience: "신입",
        expMin: 0,
        scores: {salary:35,welfare:52,growth:55,balance:72,career:42,stability:38},
        education: "학력무관",
        deadline: "2026-05-10",
        tags: ["테스트자동화", "Selenium", "게임QA"],
        lat_offset: -0.0430,
        lng_offset: +0.0450,
        address: "경기 성남시 분당구",
        employees: "4,000명+",
        rating: 3.8,
        welfare_items: ["게임 제공", "자기계발비", "복지포인트"],
        work_style: ["하이브리드", "주 2회 재택"],
    },
    // 거리: ~8.0km | 프리랜서 | 이커머스 | 상시채용
    {
        id: 16,
        name: "지마켓",
        logo: "🏪",
        industry: "이커머스",
        position: "데이터 사이언티스트",
        type: "프리랜서",
        salary: "6,000 ~ 8,000만원",
        minSalary: 6000,
        experience: "3년 이상",
        expMin: 3,
        scores: {salary:78,welfare:58,growth:60,balance:48,career:68,stability:62},
        education: "학력무관",
        deadline: "상시채용",
        tags: ["Python", "추천시스템", "빅데이터"],
        lat_offset: +0.0510,
        lng_offset: +0.0510,
        address: "서울 강남구",
        employees: "1,800명+",
        rating: 3.9,
        welfare_items: ["쇼핑 할인", "성과급", "간식 제공"],
        work_style: ["사무실 근무", "자율 출퇴근"],
    },
    // 거리: ~9.5km | 정규직 | 핀테크
    {
        id: 17,
        name: "삼성카드",
        logo: "💴",
        industry: "핀테크",
        position: "앱 개발자 (Android)",
        type: "정규직",
        salary: "5,500 ~ 8,500만원",
        minSalary: 5500,
        experience: "3년 이상",
        expMin: 3,
        scores: {salary:76,welfare:70,growth:55,balance:55,career:72,stability:90},
        education: "학력무관",
        deadline: "2026-06-15",
        tags: ["Kotlin", "금융앱", "보안"],
        lat_offset: -0.0600,
        lng_offset: +0.0620,
        address: "서울 서초구",
        employees: "10,000명+",
        rating: 3.9,
        welfare_items: ["금융 우대", "사내 의원", "자녀 교육비", "경조사 지원"],
        work_style: ["사무실 근무", "주 5일", "안정적 환경"],
    }
];